### ISSUE TITLE
Installation fails due to difference in package name and repository name. (eaf-vue-tailwindcss vs eaf-tailwindcss)

### ISSUE THREAD

**Issue by jehuamanna** [emacs-eaf/eaf-vue-tailwindcss#2]
The repository name is `eaf-vue-tailwindcss` which automatically get picked up by the installation to display a documentation to install the package as `(require 'eaf-vue-tailwindcss)` which is inconsistent with the provided package name `eaf-tailwindcss`.

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "eaf-vue-tailwindcss")
  require(eaf-vue-tailwindcss)
  (setq elisp--eval-defun-result (require 'eaf-vue-tailwindcss))
  elisp--eval-defun()
  eval-defun(nil)
  funcall-interactively(eval-defun nil)
  command-execute(eval-defun)
```

**Comment by manateelazycat** [comment]
Fixed by https://github.com/emacs-eaf/eaf-vue-tailwindcss/commit/ad115fd1f29a74e00780aeb75de20637ba003121

Thanks for report. ;)
